// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import ScrollDownController from "./scroll_down_controller.js"
application.register("scroll-down", ScrollDownController)

import MapController from "./map_controller.js"
application.register("map", MapController)
